name: Request a  new environment
description: This issue allows you to request a new environment'
title: "Ops - Request a new environment"
labels: ["ops","ops-env-request"]
body:
  - type: input
    id: type
    attributes:
      label: Provide the type of the environment
      description: Valid values are one of  dev / test /release
  - type: input
    id: name
    attributes:
      label: Provide the name of the org
      description: Provide the name of the org, Any name more than 10 characters will be truncated, if the org is not can be authenticated using the authenticated devhub user, you will need to set up a SB_SFDX_AUTH_URL secret in the environment
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: Provide the branch associated with the org
      description: The org will be associated with artifacts released from this branch
    validations:
      required: true
  - type: input
    id: envApprover
    attributes:
       label: Do you want an environment approval for this org?
       description: If yes, please enter the github handle of the approvers, Multiple users can be seperated by commas



