name: Request a sfp artifact installation
description: This issue allows to install a sfp artifact to a target org
title: "Ops - Install an sfp artifact to an org(s)"
labels: ["ops", "ops-sfp-artifact-installation-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Instructions!

        This issue template is used to install an artifact into an org that is created by buildbot 
        or an org that is registred in Github Environments

        ## :warning: Warnings!
        - Please use this issue sparingly and try to use release candidates whenever possible
        - Use this  issue to deploy technical artifacts or artifacts that are indpendent and do not belong to a domain

  - type: input
    id: orgnames
    attributes:
      label: Name of the org(s)
      description: Please provide the name of the org(s), Only orgs that are created by build bot or available in the env can be used
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Environment Profile
      description: Environment profiles define the type of metadata for aliasifed packages, Select an env orgs as mentioned in sfdx-project.json , For example ci, qa, uat, prod
    validations:
      required: true
  - type: input
    id: packageName
    attributes:
      label: Name of the package?
      description: Please provide the name of the package to be installed, the name of the package has to match what is your Github Packages
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version of the package?
      description: Please provide the full version of the package as seen in your  Github Packages, such as 1.0.0-232323
    validations:
      required: true
  # - type: dropdown
  #   id: installationmode
  #   attributes:
  #     label: Pick an installation mode if the requested package is unlocked package
  #     description: Unlocked package has various installation mopdes, please pick one
  #     options:
  #       - delete-only
  #       - deprecate-only
  #       - mixed-mode
  - type: checkboxes
    id: forceInstall
    attributes:
      label: Do you want to force install the package?
      description: If you want to force install the package, please select yes
      options:
        - label: "yes"