releaseName: frameworks
domainNameUsedForPools: CORE
excludeAllPackageDependencies: true 
includeOnlyArtifacts:
# orgshape and core-objects are shared so added here as well
  - feature-management
releasedefinitionProperties:
  promotePackagesBeforeDeploymentToOrg: prod
  skipIfAlreadyInstalled: true
  changelog:
    workItemFilters:
      -  (FGK|FFK)-[0-9]{3,4}
    workItemUrl: https://adiza.atlassian.net/browse
    limit: 30