# build all packages


name: 'Build-main'


on:
  push:
    branches:
      - main

  workflow_dispatch:



#Set the environment variables for tracking metrics
env:
  SFPOWERSCRIPTS_DATADOG: 'true'
  SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'


jobs:
  analyze:
    name: 'Analyze Impacted Domains'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Figure out the last tagged commit id
        id: commit-finder
        run: |
            last_tag=$(git describe --tags --match '*_v*' --abbrev=0 2>/dev/null || true)

            if [ -z "$last_tag" ]; then
              echo "No tags found."
              echo "last_tagged_commit=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT
            else
              echo "Tag found: $last_tag"
              echo "last_tagged_commit=$(git rev-parse $last_tag)" >> $GITHUB_OUTPUT
            fi
        

      - name: 'Figure Impacted Release Defns'
        uses: flxbl-io/sfops-gh-actions/impactedReleaseDefnDetector@main
        with:
         pathToReleaseDefns: 'config'
         from-commit: ${{ steps.commit-finder.outputs.last_tagged_commit }}
         to-commit: HEAD
         
      - name: Set matrix data
        id: set-matrix
        run: |
           echo "matrix=$(jq -c . < ./impacted-releases.json)" >> $GITHUB_OUTPUT
  

  deploy:
    needs: 
      - analyze
    strategy:
      matrix: ${{ fromJson(needs.analyze.outputs.matrix) }}
      fail-fast: false
    uses:   flxbl-io/sfops-gh-actions/.github/workflows/build-a-domain.yml@main
    with:
       releaseconfig: ${{ matrix.filePath }}
       domain: ${{ matrix.releaseName }}
       branchname: main
       allReleaseNames: ${{ matrix.allReleaseNames }}
       dashboard-repo: sfops-dashboard
       releasename: ${{ vars.releaseName }}
       workitem-url: 'https://flxbl.atlassian.net'
       workitem-filter: '(ABC|DEF)-[0-9]{3,4}'
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      gh-token: ${{ secrets.GHA_TOKEN }}
      datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
      datadog-host: ${{ secrets.DATADOG_HOST }}

  