name: 'Build-hotfix'


on:
  push:
    branches:
       - 'release/**'
  workflow_dispatch:



#Set the environment variables for tracking metrics
env:
  SFPOWERSCRIPTS_DATADOG: 'true'
  SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'


jobs:
  build:
    name: 'Build packages'
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts-rc:alpha
    if: startsWith(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get domain from branch name'
        id: get-domain
        run: |
           echo "domain=$(echo ${GITHUB_REF#refs/heads/release/})" >> "$GITHUB_OUTPUT"


      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      - name: 'Create packages'
        id: sfpowerscripts-build
        run: |
          sfpowerscripts orchestrator:build -v devhub --diffcheck --branch ${{ github.ref_name }} --buildnumber ${GITHUB_RUN_ID} --releaseconfig=config/release-config-${{ steps.get-domain.outputs.domain}}.yaml

      # Publish artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: artifacts

      # Publish logs
      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: .sfpowerscripts/logs

 
  publish:
    name: 'publish'
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts-rc:alpha
    needs: 
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
            name: build-artifacts
            path: artifacts 
  
      - name: 'Get domain from branch name'
        id: get-domain
        run: |
           echo "domain=$(echo ${GITHUB_REF#refs/heads/release/})" >> "$GITHUB_OUTPUT"


      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
         registry-url: 'https://npm.pkg.github.com'

      - name: Publish
        run: |
          sfpowerscripts orchestrator:publish -d artifacts --npm --scope @${{ github.repository_owner }}  --gittag --pushgittag
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GHA_TOKEN }}
         GH_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Compute Release Name
        run: |
          echo "RELEASE_NAME=$(echo ${{ vars.RELEASENAME }}-$(date +'%d-%m')-${{github.run_id}})" >> $GITHUB_ENV


      - name: Add property to skip artifact update to org  for hotfixes
        uses: mikefarah/yq@master
        with:
           cmd: yq eval '.releasedefinitionProperties.skipArtifactUpdate = true' config/release-config-${{ steps.get-domain.outputs.domain}}.yaml -i


      - name: Generate release notes
        if: always()
        run: |
           sfpowerscripts releasedefinition:generate -b releasedefns  -c  HEAD  -d orde-hotfix -f  config/release-config-${{ steps.get-domain.outputs.domain}}.yaml -n hotfix-${{ steps.get-domain.outputs.domain}}-$(date +'%d-%m')-${{github.run_id}}
           sfpowerscripts changelog:generate -b releasedefns  -d artifacts -w "{{ customer.jira_regex }}" -r "https://flxbl.atlassian.net" -n hotfix-${{ steps.get-domain.outputs.domain}}-$(date +'%d-%m')-${{github.run_id}} --directory orde-hotfix
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: 'Report changelog'
        uses: flxbl-io/sfops-gh-actions/changelogReporter@main  
        with:
         source-branch: releasedefns
         target-dir: changelog
         pathToReleaseConfigs: config
         target-repo: flxbl-io/sfops-dashboard
         gh_token: ${{ secrets.GHA_TOKEN }}
         source-repo-url: https://github.com/flxbl-io/sf-core
         workitem-url: https://flxbl.atlassian.net

      - name: 'Cherry pick the commit and create PR'
        uses: flxbl-io/sfops-gh-actions/cherrypickAndCreatePR@main
        continue-on-error: true
        with:
          git-user-email: ciuser@flxbl.io
          git-user-name: build-bot
          gh_token: ${{ secrets.GHA_TOKEN }}
          target-branch: 'main'


      - uses: mshick/add-pr-comment@v2
        with:
         message: |
             This work item  is now published in the following release defn  ${{env.RELEASE_NAME}} .
             The link is available at https://flxbl-io.github.io/changelog/changelog-hotfix.html#${{env.RELEASE_NAME}}




 
