name: 'Job - CI Sandbox - Creator'

# Read name of sandbox
on:
  workflow_dispatch:
  schedule:
      - cron: '0 */6 * * *'   

#Set the environment variables for tracking metrics
env:
  SFPOWERSCRIPTS_DATADOG: 'true'
  SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:

  delete-ci-sandboxes:
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops:latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate DevHub'
        run: |
              echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
              sfdx auth:sfdxurl:store -f authfile -a devhub

      #Create a sandbox
      - name: 'Delete CI Sandboxes'
        uses:  flxbl-io/sfops-gh-actions/deleteCISandboxes@main
        with:
          devhub_sfdx_auth_url: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
          gh_token: ${{ secrets.GHA_TOKEN }}



  create-ci-sandbox:
    runs-on: ubuntu-latest
    needs: delete-ci-sandboxes
    container: ghcr.io/flxbl-io/sfops:latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
            node-version: "18" 


      - name: Check time and exit if not within time range
        if: ${{ github.event_name == 'schedule' }}
        run: |
          # Get current hour in AEST
          HOUR=$(TZ=":Australia/Melbourne" date +"%H")
          if (( HOUR < 6 || HOUR > 20 )); then
            echo "Outside of 6 AM - 8 PM AEST, exiting"
            exit 1
          fi

      - name: 'Authenticate DevHub'
        run: |
              echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
              sfdx auth:sfdxurl:store -f authfile -a devhub

      #Create a sandbox
      - name: 'Create CI Sandboxes'
        uses:  flxbl-io/sfops-gh-actions/createCISandboxes@main
        with:
          pathToPoolConfigFile: "config/sandbox-pool-config.json"
          devhub_sfdx_auth_url: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
          gh_token: ${{ secrets.GHA_TOKEN }}



