name: 'IssueOps - Delete Components'
run-name: 'Deletion of components -${{ github.event.issue.number }}-requested by-${{ github.event.issue.user.login }}'
on:
  issues:
    types: [ opened, reopened ]

#Set the environment variables for tracking metrics
env:
  SFPOWERSCRIPTS_DATADOG: 'true'
  SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'


jobs:
  issue-analyzer:
    if: contains(github.event.issue.title, 'Ops - Deletion of a components from Org')
    runs-on: ubuntu-latest
    outputs:
      parsedEnvs: ${{ steps.issue-analyzer-output.outputs.parsedEnvs }}
      components: ${{ steps.issue-analyzer-output.outputs.components }}
      targetorg: ${{ steps.issue-analyzer-output.outputs.targetorg }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/request-component-deletion.yml

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHA_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [ "ops",  "ops-deletion-of-component"]
            })

      - name: Create Comment before initiating action
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{github.event.issue.number}}
          token: ${{ secrets.GHA_TOKEN }}
          body: |
            Hello @${{ github.event.issue.user.login }} :wave:
            
            Your request has been received and is being processed. 
            We will attempt to delete the component(s) in provided orgs using an unlocked package :), 
            and will update this issue with the results.
            You can follow the action at this link: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

      - name: Set Output
        id: issue-analyzer-output
        run: |
            echo "components=${{ steps.issue-parser.outputs.issueparser_components }}" >> "$GITHUB_OUTPUT"
            echo "targetorg=${{ steps.issue-parser.outputs.issueparser_targetorg }}" >> "$GITHUB_OUTPUT"

            IFS=',' read -r -a array <<< "${{ steps.issue-parser.outputs.issueparser_envs }}"
            output="["
            for element in "${array[@]}"
            do
             output+="\"$element\","
            done
            output="${output::-1}"
            output+="]"
            echo "parsedEnvs=$output" >> "$GITHUB_OUTPUT"
          
           


  execute_action:
    needs: issue-analyzer
    uses:  flxbl-io/sfops-gh-actions/.github/workflows/delete-component-job.yml@main
    strategy:
      fail-fast: false
      matrix:
        environment: ${{  fromJson(needs.issue-analyzer.outputs.parsedEnvs) }}
    with:
       environment:  ${{ matrix.environment }}
       components: ${{ needs.issue-analyzer.outputs.components }}
    secrets:
       SB_SFDX_AUTH_URL: ${{ secrets.SB_SFDX_AUTH_URL }}
       DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}  
      


      
  close_issue:
     runs-on: ubuntu-latest
     needs:  execute_action
     if: contains(github.event.issue.title, 'Ops - Deletion of a components from Org')
     steps:

      # gh needs a repo bummer
      - uses: actions/checkout@v3

      - name: Close Issue
        run: |
         gh issue close ${{github.event.issue.number}} -c " Hello @${{ github.event.issue.user.login }} :wave: \n Your request has been sucessfully processed" -r "Completed"
        env:
           GH_TOKEN: ${{ secrets.GHA_TOKEN }}

  comment_issue_on_error:
      runs-on: ubuntu-latest
      needs:   execute_action
      if: always() && needs.execute_action.result == 'failure'
      steps:

      - name: Create Comment after failure
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{github.event.issue.number}}
          token: ${{ secrets.GHA_TOKEN }}
          body: |
            Hello @${{ github.event.issue.user.login }} :wave:
            
            Apologies, it seems we ran into an issue, This would need your manual attention please check the job run
            at the link https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}