name: IssueOps - Delete Dev Sandbox

on:
  issues:
    types: [ closed ]



run-name: Delete sandbox for issue-${{ github.event.issue.number }}

jobs:
  delete-dev-sandbox:
    if: contains(github.event.issue.title, 'Ops - Request a new Dev Sandbox')
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops:latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Find Comment with Sandbox Name
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: "Sandbox Name:"
          direction: last
          token: ${{ secrets.GHA_TOKEN }}


      - name: Parse sandbox information
        id: parse_sandbox_info
        run: |
         comment=$( cat << 'EOF'
         ${{ steps.fc.outputs.comment-body }} 
         EOF
         )
         if [[ $comment == *"Your sandbox has been created successfully"* ]]; then
          sandbox_name=$(echo "$comment" | sed -n -e 's/^.*Sandbox Name: \(.*\)$/\1/p')
          echo "SANDBOX_NAME=$sandbox_name" >> "$GITHUB_OUTPUT"
         else
          exit 1
         fi

      - name: Attempt to Delete Sandbox
        uses: flxbl-io/sfops-gh-actions/deleteSandbox@main
        id: delete_sandbox
        with: 
          devhub_sfdx_auth_url: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
          sandboxName: ${{ steps.parse_sandbox_info.outputs.SANDBOX_NAME }}
          
      - name: Reopen Issue if Sandbox Deletion Failed
        if: steps.delete_sandbox.outputs.DELETED == 'false' || failure()
        run: |
          # Install gh cli

          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
         
          gh
          gh issue reopen  ${{ github.event.issue.number }}
          gh issue comment ${{ github.event.issue.number }} -b "Sandbox deletion failed probably due to not reaching the 24 hour limit, hence we are reopening the issue. We will attempt it at the next run, Please check the logs here  Please check the logs at https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
        
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}  

      - uses: actions/github-script@v6
        if: steps.delete_sandbox.outputs.DELETED == 'false' || failure()
        with:
          github-token: ${{ secrets.GHA_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [ "ops","ops-sandbox-request-delete-failed"]
            })
        