name: PR - Jira Lint
on: [pull_request]

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: cleartax/jira-lint@master
        name: jira-lint
        with:
          github-token: ${{ secrets.GHA_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://wingategroup.atlassian.net
          skip-branches: '^(release|release\/v\d+)$'
          skip-comments: true
          pr-threshold: 1000