name: 'sfops - CI Sandbox - Creator'

# Read name of sandbox
on:
  workflow_dispatch:
  schedule:
      - cron: '0 6 * * *'   

#Set the environment variables for tracking metrics
env:
  SFPOWERSCRIPTS_DATADOG: 'true'
  SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:

  create-ci-sandbox:
    name: 'Create CI Sandboxes'
    uses:   flxbl-io/sfops-gh-actions/.github/workflows/sandbox-pool-creator.yml@main
    with:
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
      path-to-config : "config/sandbox-pool-config.json"
      dashboard-repo:  ${{ vars.SFOPS_DASBHOARD_REPO }}
      metrics-provider: ${{ vars.SFOPS_METRICS_PROVIDER }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}    


