name: "sfops - On Pull Request Comments"

on:
  issue_comment:
    types: [created]

jobs:
  build-deploy:
    name: "Deploy branch to test environments"
    uses: flxbl-io/sfops-gh-actions/.github/workflows/branch-deploy.yml@main
    if: ${{ github.event.issue.pull_request && ( startsWith(github.event.comment.body, 'sfops forcetest') || startsWith(github.event.comment.body, 'sfops test') || (startsWith(github.event.comment.body, 'sfops unlock'))) }}
    with:
      pathToReleaseConfigs: "config"
      dashboard-repo: ${{ vars.SFOPS_DASBHOARD_REPO }}
      releasename: ${{ vars.releaseName }}
      metrics-provider: ${{ vars.SFOPS_METRICS_PROVIDER }}
      workitem-url: ${{ vars.SFOPS_ISSUETRACKER_URL }}
      workitem-filter: ${{ vars.SFOPS_ISSUETRACKER_WORKITEM_FILTER }}
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      SB_SFDX_AUTH_URL: ${{ secrets.SB_SFDX_AUTH_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  renew-org:
    name: "Renew Sandbox and retrigger validation"
    uses: flxbl-io/sfops-gh-actions/.github/workflows/exec-renew-review-org.yml@main
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, 'sfops renew')  }}
    with:
      issue-number: ${{ github.event.issue.number }}
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
