name: "sfops - On Pull Request Comments"

on:
  issue_comment:
    types: [created]

jobs:

  analyze:
    name: "Analyze Impacted Domains"
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfops-lite:latest
    if: ${{ github.event.issue.pull_request && ( startsWith(github.event.comment.body, 'sfops commit') || (startsWith(github.event.comment.body, 'sfops unlock'))) }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_sha }}


      - name: "Figure Impacted Release Defns"
        uses: flxbl-io/sfops-gh-actions/impactedReleaseDefnDetector@main
        with:
          pathToReleaseDefns: "config"
          from-commit: ${{ steps.comment-branch.outputs.base_sha }}
          to-commit:  ${{ steps.comment-branch.outputs.head_sha }}

      - name: Set matrix data
        id: set-matrix
        run: |
          cat impacted-release-configs.json
          echo "matrix=$(jq -c . < ./impacted-release-configs.json)" >> $GITHUB_OUTPUT

  deploy-lock:
    if: ${{ needs.analyze.outputs.matrix != '[]' &&  github.event.issue.pull_request &&  startsWith(github.event.comment.body, 'sfops commit') }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.analyze.outputs.matrix) }}
      fail-fast: false
    needs: 
      - analyze
    outputs:
      continue: ${{ steps.branch-deploy.outputs.continue }}
      issue-number: ${{ github.event.issue.number }}
      branch-ref: ${{ steps.branch-deploy.outputs.ref }}
      locked: ${{ steps.lock.outputs.locked }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        name: "Get installation token for sfopsbot"
        with:
          app-id: ${{ vars.SFOPSBOT_APP_ID }}
          private-key: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

         

      - uses: flxbl-io/sfops-gh-actions/lock@main
        id: lock_check
        with:
         mode: 'check'
         environment: 'test-${{ matrix.releaseName }}'
         environment_targets: 'test-${{ matrix.releaseName }}'
         github_token: ${{steps.app-token.outputs.token}}

      - name: If a lock already exists
        if: ${{ steps.lock_check.outputs.locked == 'true' }}
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d 
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Deployment In Progress

            Hello @${{ github.event.issue.user.login }} :wave:

            There is another deployment in progress, please request deployment after some time.
            
            Deploment locked for   **${{steps.lock_check.outputs.branch}}** by **${{steps.lock_check.outputs.created_by}}**


      - name: branch-deploy
        id: branch-deploy
        if: ${{ steps.lock_check.outputs.locked != 'true' }}
        uses: flxbl-io/sfops-gh-actions/branchDeploy@main
        with:
          reaction: "eyes"
          stable_branch: "main"
          github_token: ${{steps.app-token.outputs.token}}
          environment: test-${{ matrix.releaseName }}
          skip_ci: test-${{ matrix.releaseName }}
          skip_reviews: test-${{ matrix.releaseName }}
          skip_completing: 'true'
    

      - uses: flxbl-io/sfops-gh-actions/lock@main
        id: lock
        if: ${{ steps.lock_check.outputs.locked != 'true' }}
        with:
         mode: 'lock'
         environment: 'test-${{ matrix.releaseName }}'
         environment_targets: 'test-${{ matrix.releaseName }}'
         github_token: ${{steps.app-token.outputs.token}}

  deploy-unlock:
    if: ${{ github.event.issue.pull_request &&  startsWith(github.event.comment.body, 'sfops unlock') }}
    runs-on: ubuntu-latest
    needs:
      - analyze
    strategy:
      matrix: ${{ fromJson(needs.analyze.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        name: "Get installation token for sfopsbot"
        with:
          app-id: ${{ vars.SFOPSBOT_APP_ID }}
          private-key: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: flxbl-io/sfops-gh-actions/lock@main
        id: unlock
        with:
         mode: 'unlock-on-comment'
         environment: 'test-${{ matrix.releaseName }}'
         environment_targets: 'test-${{ matrix.releaseName }}'
         github_token: ${{steps.app-token.outputs.token}}

  



  build-deploy:
    name: "Deploy ${{ matrix.releaseName }} to test environments"
    needs:
      - analyze
      - deploy-lock
    if: ${{ needs.analyze.outputs.matrix != '[]'  && needs.deploy-lock.outputs.continue == 'true'}}
    strategy:
      matrix: ${{ fromJson(needs.analyze.outputs.matrix) }}
      fail-fast: false
      max-parallel: 1
    uses: flxbl-io/sfops-gh-actions/.github/workflows/build-test-domain.yml@main
    with:
      releaseconfig: ${{ matrix.filePath }}
      domain: ${{ matrix.releaseName }}
      branchname: ${{ github.ref_name }}
      branch-ref: ${{ needs.deploy-lock.outputs.branch-ref }}
      pathToReleaseConfigs: "config"
      dashboard-repo: ${{ vars.SFOPS_DASBHOARD_REPO }}
      releasename: ${{ vars.releaseName }}
      metrics-provider: ${{ vars.SFOPS_METRICS_PROVIDER }}
      workitem-url: ${{ vars.SFOPS_ISSUETRACKER_URL }}
      workitem-filter: ${{ vars.SFOPS_ISSUETRACKER_WORKITEM_FILTER }}
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      SB_SFDX_AUTH_URL: ${{ secrets.SB_SFDX_AUTH_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  result:
    needs: [deploy-lock, build-deploy]
    runs-on: ghcr.io/flxbl-io/sfops-lite:latest
    # run even on failures but only if the trigger job set continue to true
    if: ${{ always() && needs.deploy-lock.outputs.continue == 'true' }}

    steps:
      # if a previous step failed, set a variable to use as the deployment status
      - name: set deployment status
        id: deploy-status
        if: ${{ needs.deploy-lock.result == 'failure' || needs.build-deploy.result == 'failure' }}
        run: |
          echo "DEPLOY_STATUS=failure" >> $GITHUB_OUTPUT

      # use the GitHub CLI to update the deployment status that was initiated by the branch-deploy action
      - name: Create a deployment status
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          DEPLOY_STATUS: ${{ steps.deploy-status.outputs.DEPLOY_STATUS }}
        run: |
          if [ -z "${DEPLOY_STATUS}" ]; then
            DEPLOY_STATUS="success"
          fi

          gh api \
            --method POST \
            repos/{owner}/{repo}/deployments/${{ needs.deploy-lock.outputs.deployment_id }}/statuses \
            -f environment='${{ needs.deploy-lock.outputs.environment }}' \
            -f state=${DEPLOY_STATUS}



      # remove the default 'eyes' reaction from the comment that triggered the deployment
      # this reaction is added by the branch-deploy action by default
      - name: remove eyes reaction
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method DELETE \
            repos/{owner}/{repo}/issues/comments/${{ needs.deploy-lock.outputs.comment_id }}/reactions/${{ needs.deploy-lock.outputs.initial_reaction_id }}

      # if the deployment was successful, add a 'rocket' reaction to the comment that triggered the deployment
      - name: rocket reaction
        if: ${{ steps.deploy-status.outputs.DEPLOY_STATUS != 'failure' }}
        uses: GrantBirki/comment@e6bf4bc177996c9572b4ddb98b25eb1a80f9abc9 # pin@v2.0.7
        with:
          comment-id: ${{ needs.deploy-lock.outputs.comment_id }}
          reactions: rocket

      # if the deployment failed, add a '-1' (thumbs down) reaction to the comment that triggered the deployment
      - name: failure reaction
        if: ${{ steps.deploy-status.outputs.DEPLOY_STATUS == 'failure' }}
        uses: GrantBirki/comment@e6bf4bc177996c9572b4ddb98b25eb1a80f9abc9 # pin@v2.0.7
        with:
          comment-id: ${{ needs.deploy-lock.outputs.comment_id }}
          reactions: '-1'

      # if the deployment was successful, add a 'success' comment
      - name: success comment
        if: ${{ steps.deploy-status.outputs.DEPLOY_STATUS != 'failure' }}
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d # pin@v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Deployment Results ✅

            **${{ needs.deploy-lock.outputs.actor_handle }}** successfully deployed branch `${{ needs.deploy-lock.outputs.ref }}` to **${{ needs.deploy-lock.outputs.environment }}**

      # if the deployment was not successful, add a 'failure' comment
      - name: failure comment
        if: ${{ steps.deploy-status.outputs.DEPLOY_STATUS == 'failure' }}
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d # pin@v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Deployment Results ❌

            **${{ needs.deploy-lock.outputs.actor_handle }}** had a failure when deploying `${{ needs.deploy-lock.outputs.ref }}` to **${{ needs.deploy-lock.outputs.environment }}**
