name: sfops - Jira Lint on Pull Request
on: [pull_request]

jobs:
 lint-jira:
    name: 'Lint JIRA Taks in a PR'
    uses:   flxbl-io/sfops-gh-actions/.github/workflows/pr-jira-lint.yml@main
    with:
      jira-user:  ${{ vars.SFOPS_JIRA_USER }}
      jira-base-url: ${{ vars.SFOPS_ISSUETRACKER_URL_BASE }}
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
      metrics-provider:  ${{ vars.SFOPS_METRICS_PROVIDER }}
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      SFOPSBOT_JIRA_TOKEN: ${{ secrets.SFOPS_JIRA_TOKEN }}
