name: 'sfops - Report results of all quality tests'

# Read name of sandbox
on:
  workflow_dispatch:
  schedule:
      - cron: '0 12 * * *' # At 12 00 UTC every day

      
run-name: 'sfops- Execute Daily Quality Tests'

jobs:

  apex-test-runs:
    name: 'Run All Apex Tests on All Test Envs'
    uses:   flxbl-io/sfops-gh-actions/.github/workflows/apex-test-on-test-envs.yml@main
    with:
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
      dashboard-repo:  ${{ vars.SFOPS_DASBHOARD_REPO }}
      metrics-provider: ${{ vars.SFOPS_METRICS_PROVIDER }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

  static-analysis:
    name: 'Run Static Analysis  on Repo'
    uses:   flxbl-io/sfops-gh-actions/.github/workflows/static-analysis.yml@main
    with:
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
      dashboard-repo:  ${{ vars.SFOPS_DASBHOARD_REPO }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
