name: PR - Jira Lint
on: [pull_request]

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
           app-id: ${{ vars.SFOPSBOT_APP_ID }}
           private-key: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}


      - uses: cleartax/jira-lint@master
        name: jira-lint
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://wingategroup.atlassian.net
          skip-branches: '^(release|release\/v\d+)$'
          skip-comments: true
          pr-threshold: 1000