name: 'sfops - Replenish CI Pools (ScratchOrg)'

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: "Commit Id from where the pools should be created"
        required: false
        default: 'main'
  schedule:
    - cron: '0 14 * * *'



jobs:

  pool-ci-pool:
    name: 'Create CI Scratch Org Pool'
    uses:   flxbl-io/sfops-gh-actions/.github/workflows/scratch-org-pool-creator.yml@main
    with:
      path-to-config : "config/scratch-ci-pool.json"
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
      dashboard-repo:  ${{ vars.SFOPS_DASBHOARD_REPO }}
      metrics-provider: ${{ vars.SFOPS_METRICS_PROVIDER }}
      git-ref: ${{ github.event.inputs.gitRef }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}    



