name: sfops - Daily job executer
on:
  schedule:
    - cron: '0 12 * * *' # At 12 00 UTC every day
  workflow_dispatch:

run-name: 'sfops- Execute Daily Jobs'

jobs:
  exec-daily-reports:
      name: 'Publish Reports'
      uses:   flxbl-io/sfops-gh-actions/.github/workflows/exec-daily-jobs.yml@main
      with:
         sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
         metrics-provider: ${{ vars.SFOPS_METRICS_PROVIDER }}
      secrets:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
        SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}

