name: 'sfops - Scratch Org Pool Cleaner'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'


jobs:

  clean-pool-ci:
    name: 'Drop CI Pool'
    uses:   flxbl-io/sfops-gh-actions/.github/workflows/scratch-org-pool-cleaner.yml@main
    with:
      pool-name: ci
      drop-all-orgs: true
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
      dashboard-repo:  ${{ vars.SFOPS_DASBHOARD_REPO }}
      metrics-provider: ${{ vars.SFOPS_METRICS_PROVIDER }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

  clean-pool-dev:
    name: 'Drop DEV Pool'
    uses:   flxbl-io/sfops-gh-actions/.github/workflows/scratch-org-pool-cleaner.yml@main
    with:
      pool-name: dev
      drop-all-orgs: false
      sfopsbot-app-id: ${{ vars.SFOPSBOT_APP_ID }}
      dashboard-repo:  ${{ vars.SFOPS_DASBHOARD_REPO }}
      metrics-provider: ${{ vars.SFOPS_METRICS_PROVIDER }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_HOST: ${{ secrets.DATADOG_HOST }}
      SFOPSBOT_APP_PRIVATE_KEY: ${{ secrets.SFOPSBOT_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

